spring:
  application:
    name: mqtt-subscriber
  # Spring Integration MQTT 配置
  mqtt:
    host: tcp://localhost:11883
    client-id: mqtt-server-${random.value}
    topic: device/+/reporter
    qos: 1
    username: mqtt_user
    password: mqtt_password
  
  # H2 数据库配置（设备信息）
  datasource:
    h2:
      url: jdbc:h2:mem:device_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: 
      driver-class-name: org.h2.Driver
    clickhouse:
      url: jdbc:clickhouse://localhost:8123/mqtt_db
      username: default
      password:
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  
  # JPA 配置（仅用于 H2）
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

logging:
  level:
    root: INFO
    org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
